### ISSUE TITLE
Bot records empty lines

### ISSUE THREAD

**Issue by ikoutone** [MJHeijster/StatBot#60]
# Bug

Bot version is latest, 1.6.0

## Expected behavior
Record full line of text
On discord:
16:35]Ile: Testing if the bot broke since it is showing empty lines from today in the log

## Actual behavior
It only records channel, timestamp and who says the line but actual line is not there. This started happening in the last 24 hours or so.
#general - [2022-09-03 13:35:18] <Ilkka#1111>

## Steps to reproduce
Start bot and someone says something

## Logs
> If you have an exception or log, please provide it.

# Feature
Please explain what you want it to do, what isnt happening yet. You can also discuss it on Discord https://discord.gg/SFYVQNE

**Comment by ikoutone** [comment]
Hey @MJHeijster. Any plans to fix the bot?

**Comment by MJHeijster** [comment]
@ikoutone sorry about my absense, got a lot going on irl. It turns out my bot also had this issue. If you login to the discord developer page (https://discord.com/developers/applications) and select your bot, go to "Bot" in the left menu and enable "Message Content Intent". In my short test, I had to restart the bot, but that might not be needed. I understand that it was announced a year ago, but I also wasn't aware of it.

**Comment by ikoutone** [comment]
Restart was needed after I enabled the message content intent setting. Thank you for the help once again :)
